# Logging settings.
logging:
  level: INFO
  # Logger-specific levels.
  loggers:
    # Sets the level for 'com.example.app' to DEBUG.
    com.galaxy: INFO
    # Redirects SQL logs to a separate file
    #org.hibernate.SQL:
      #level: DEBUG
  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /var/log/app/galaxy/galaxy.log
      archivedLogFilenamePattern: /var/log/app/galaxy/galaxy-%d{yyyy-MM-dd}.log.gz
      archivedFileCount: 7
      timeZone: UTC+5:30

server:
  applicationConnectors:
    - type: http
      port: 9098
  adminConnectors:
    - type: http
      port: 9099
  rootPath: /galaxy

elasticsearchConfiguration:
  host: search-my-domain-wqe5n4e4iipkps2yjae4sc5twq.ap-south-1.es.amazonaws.com
  port:

swagger:
  resourcePackage: com.galaxy.resources

awsConfig:
  accesskey: "aa"
  secretaccesskey: "ss"
  clientregion: "sdd"
  bucketname: "dad"
